server:
  port: 80
#数据库配置
spring:
  datasource:
    name: mytest
    #serverTimezone设置时区
    url:  jdbc:mysql://127.0.0.1:3306/mytest?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

#mybatis配置
mybatis:
  configLocation: classpath:mybatis-config.xml
#  mapper-locations: com.example.mapper
  type-aliases-package: com.example.bean


  redis:
#    Redis数据库索引（默认为0）
    database: 0
#    Redis服务地址
    host: localhost
#    Redis服务器连接端口
    port: 6379
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
#     连接超时
    timeout: 0

logging:
  level:
    com:
      example:
        mapper: debug