spring:
  aop:
    proxy-target-class: true
  datasource:
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    #      使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/shirojwt?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    name: ShiroJwt
  resources:
    static-locations: classpath:/
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    servlet:
      content-type: text/html

#mappers 多个接口时都好隔开
mapper:
  mappers: com.czw.browser.data.util.MyMapper
  not-empty: false
  identity: mysql

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.czw.browser.data.model.entity
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE
  config-location: classpath:mybatisConfig.xml


logging:
  #  Debug打印SQL
  level.com.xyx.shiro.mapper: debug
server:
  port: 80
  servlet:
    context-path: /browserServer

