
spring:
  aop:
    proxy-target-class: true
  datasource:
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    #      使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/shirojwt?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    name: ShiroJwt
  resources:
    static-locations: classpath:/
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    servlet:
      content-type: text/html

#mappers 多个接口时都好隔开
mapper:
  mappers: com.example.demo.util.MyMapper
  not-empty: false
  identity: mysql

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.example.demo.moder.entity
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE
  config-location: classpath:mybatisConfig.xml

pagehelper:
  params: count=countSql
  #  指定分页插件使用哪种方言
  auto-dialect: mysql
  #  分页合理化参数 pageNum<=0时会查询第一页，pageNum>pages会查询最后一页
  reasonable: 'true'
  support-methods-arguments: 'true'
logging:
  #  Debug打印SQL
  level.com.xyx.shiro.mapper: debug
server:
  port: 80

security:
  oauth2:
    client-id: demo
    client-secret: 123456
      # 当用户未登录时,需要将其引导到该认证服务器地址, 获取授权码
    user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      # 获取token的地址
    access-token-uri: http://127.0.0.1:9999/server/oauth/token
  resource:
    jwt:
      # 获取认证服务器的签名密钥的uri
      key-uri: http://127.0.0.1:9999/server/oauth/token_key
