server:
  port: 9999
spring:
#  导入其他yml配置，一般application-**.yml命名
  profiles:
    include: pageParams
#  datasource:
#    url: jdbc:mysql://localhost/product_master?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    name: master
#    password: root
#    port: 3306
#    username: root
  aop:
    proxy-target-class: true
  datasource:
    hikari:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost/product_master?characterEncoding=utf-8&serverTimezone=GMT%2B8
        name: master
        password: root
        port: 3306
        username: root
      slave-beta:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost/product_slave_beta?characterEncoding=utf-8&serverTimezone=GMT%2B8
        name: SlaveBeta
        password: root
        port: 3306
        username: root
      slave-gamma:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost/product_slave_gamma?characterEncoding=utf-8&serverTimezone=GMT%2B8
        name: SlaveGamma
        password: root
        port: 3306
        username: root
    type: com.zaxxer.hikari.HikariDataSource

#mappers 多个接口时逗号隔开
mapper:
  mappers: com.hello.dynamicdatasource.util.MyMapper
  not-empty: false
  identity: mysql

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.hello.dynamicdatasource.beans
  # mapper xml实现扫描路径
  mapper-locations: classpath:mappers/*.xml
  property:
    order: BEFORE
  config-location: classpath:config/mybatisConfig.xml

pagehelper:
  helperDialect: mysql
  pagehelper: reasonable=true
  supportMethodsArguments: true
  params: count=countSql