server:
  port: 9999
spring:
  #  导入其他yml配置，一般application-**.yml命名
  profiles:
    include:
  aop:
    proxy-target-class: true
  datasource:
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#      使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/shirojwt?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    name: ShiroJwt
#    404交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
#404交给异常处理器处理
  resources:
    add-mappings: false
#mappers 多个接口时都好隔开
mapper:
  mappers: com.xyx.shiro.util.MyMapper
  not-empty: false
  identity: mysql

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.xyx.shiro.model.entity
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE
  config-location: classpath:mybatisConfig.xml

pagehelper:
  params: count=countSql
  #  指定分页插件使用哪种方言
  auto-dialect: mysql
#  分页合理化参数 pageNum<=0时会查询第一页，pageNum>pages会查询最后一页
  reasonable: 'true'
  support-methods-arguments: 'true'
logging:
#  Debug打印SQL
  level.com.xyx.shiro.mapper: debug